In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
% matplotlib inline

In [2]:
#データセットの読み込み
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [3]:
x=np.array(train.iloc[:,0:270])
x[:1]

array([[  1.40000000e+01,   1.60000000e+01,   6.00000000e+00,
          9.60000000e+01,   4.20000000e+01,   2.00000000e+00,
          1.96000000e+02,   2.00000000e+00,   5.00000000e+00,
          2.00000000e+00,   8.56000000e+02,   4.00000000e+00,
          8.56000000e+02,   1.71000000e+03,   2.00000000e+00,
          2.00000000e+00,   7.00000000e+00,   0.00000000e+00,
          4.00000000e+00,   8.40000000e+01,   1.00000000e+00,
          2.00000000e+00,   5.48000000e+02,   2.08500000e+05]])

In [4]:
y=np.array(train.loc[:,["SalePrice"]])
y

array([[ 208500.],
       [ 181500.],
       [ 223500.],
       ..., 
       [ 266500.],
       [ 142125.],
       [ 147500.]])

In [5]:
#変数の標準化を行う
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_std=sc.fit_transform(x)
y_std=sc.fit_transform(y)

In [6]:
#標準化した説明関数の平均が０に近いかを確認
x_std.mean()

-1.0139023055937502e-19

In [7]:
#標準化した説明関数の標準偏差を１に近いか確認
x_std.std()

1.0

In [8]:
from sklearn.linear_model import LinearRegression
lr= LinearRegression()
lr_std=LinearRegression()
lr_std.fit(x_std,y_std)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [9]:
#標準回帰係数を出力（値が大きいほどこそ影響力が大きい）
lr_std.coef_

array([[  1.66769632e-16,   1.66533454e-16,   6.80011603e-16,
          1.66533454e-16,  -1.66533454e-16,  -9.71445147e-17,
          3.60822483e-16,   2.68882139e-16,   3.79904441e-16,
          6.52256027e-16,   4.19803081e-16,   5.27355937e-16,
          1.38777878e-16,   2.49800181e-16,  -1.44632570e-16,
          2.01227923e-16,   6.93889390e-16,  -3.74700271e-16,
          1.11022302e-16,   4.44089210e-16,   6.93889390e-16,
          4.71844785e-16,  -9.36750677e-17,   1.00000000e+00]])

In [10]:
df_data = pd.DataFrame(lr_std.coef_, columns=train.columns[0:270] ,index=["A"])

In [12]:
df_data.T.sort_values(by=["A"], ascending=False).head(10)

A
SalePrice     1.000000e+00
GarageFinish  6.938894e-16
TotRmsAbvGrd  6.938894e-16
OverallQual   6.800116e-16
BsmtQual      6.522560e-16
HeatingQC     5.273559e-16
GarageCars    4.718448e-16
GarageYrBlt   4.440892e-16
TotalBsmtSF   4.198031e-16
Foundation    3.799044e-16

In [ ]:
#途中になってる